server:
   port: 5555
spring:
   application:
      name: api-gateway
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
#引入spring cloud eureka之后会自动创建默认路由规则，此处可以省略   
zuul:
  routes:
    crm-member: /crm-member/**
    crm-card: /crm-card/**
    crm-point: /crm-point/**
  